name: CI

on:
  push:
    branches: [ "develop" ]
  pull_request:
    branches: [ "develop" ]

jobs:
  build:
    runs-on: ubuntu-latest
    services:
      docker:
        image: docker:20.10.24-dind
        options: --privileged
        ports:
          - 3306:3306

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Docker Compose
        uses: docker/setup-buildx-action@v3

      - name: Build and start containers
        run: docker-compose up -d --build

      - name: Wait for MySQL to be ready
        run: |
          echo "Waiting for MySQL..."
          docker-compose exec db sh -c 'until mysqladmin ping -h "localhost" --silent; do sleep 2; done'

      - name: Run Java app
        run: |
          docker-compose exec app java -cp target/classes:$(find ~/.m2/repository -name '*.jar' | tr '\n' ':') imc.com.App

      - name: Tear down containers
        run: docker-compose down
