name: A workflow for my Hello World App
on: push

jobs:
  build:
    name: Hello world action
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'adopt'
      - name: Setup network
        run: |
          docker network create --driver bridge waimar-lab2test
          docker pull mongo
          docker run -d --name mongo-dbserver --network waimar-lab2test mongo
      - name: Build with Maven
        run: mvn package
      - name: Build
        run: docker build -t waimar-lab2test
      - name: Run image
        run: docker run --network waimar-lab2test --name semcontainer waimar-lab2test
      - name: view logs
        run: docker logs semcontainer
